% Author: Edward James, PhD Student, UCL, October 2018.
% e.james.14@ucl.ac.uk

% Tests function unwrap8BitRawDataFile.m on eight data files in 
% \Shared Data Folder\D2_DCS_AOT\DCS_flow and saves unwrapped data to 
% \Unwrapped_Data\

clearvars
clc
close all

%% D2_DCS_AOT\DCS_flow data
path_name = 'C:\Users\edggj\Dropbox\desktop\PhD\Data Analysis\Shared Data Folder\D2_DCS_AOT\DCS_flow\';

%% Sample 1
file_name = 'ej_10nm_5mW_posAA.dat'; 
% NB assume 10nm is a typo here - should read 10mm!!
% extract raw data
[f,T,duration,n,num_photons,abs_photon_times_clock,abs_photon_times_seconds, ...
    rel_photon_times_clock, rel_photon_times_seconds] ...
    = unwrap8BitRawDataFile(path_name,file_name);
% save raw data
save Unwrapped_Data\D2_DCS_AOT_DCS_flow_sample_1 f T duration n num_photons ...
    abs_photon_times_clock abs_photon_times_seconds rel_photon_times_clock ...
    rel_photon_times_seconds

%% Sample 2
file_name = 'ej_10nm_5mW_posBA.dat'; 
% extract raw data
[f,T,duration,n,num_photons,abs_photon_times_clock,abs_photon_times_seconds, ...
    rel_photon_times_clock, rel_photon_times_seconds] ...
    = unwrap8BitRawDataFile(path_name,file_name);
% save raw data
save Unwrapped_Data\D2_DCS_AOT_DCS_flow_sample_2 f T duration n num_photons ...
    abs_photon_times_clock abs_photon_times_seconds rel_photon_times_clock ...
    rel_photon_times_seconds

%% Sample 3
file_name = 'ej_10nm_5mW_posCA.dat'; 
% extract raw data
[f,T,duration,n,num_photons,abs_photon_times_clock,abs_photon_times_seconds, ...
    rel_photon_times_clock, rel_photon_times_seconds] ...
    = unwrap8BitRawDataFile(path_name,file_name);
% save raw data
save Unwrapped_Data\D2_DCS_AOT_DCS_flow_sample_3 f T duration n num_photons ...
    abs_photon_times_clock abs_photon_times_seconds rel_photon_times_clock ...
    rel_photon_times_seconds

%% Sample 4
file_name = 'ej_10nm_5mW_posDA.dat'; 
% extract raw data
[f,T,duration,n,num_photons,abs_photon_times_clock,abs_photon_times_seconds, ...
    rel_photon_times_clock, rel_photon_times_seconds] ...
    = unwrap8BitRawDataFile(path_name,file_name);
% save raw data
save Unwrapped_Data\D2_DCS_AOT_DCS_flow_sample_4 f T duration n num_photons ...
    abs_photon_times_clock abs_photon_times_seconds rel_photon_times_clock ...
    rel_photon_times_seconds

%% Sample 5
file_name = 'sp_10mm_5mW_posAA.dat'; 
% extract raw data
[f,T,duration,n,num_photons,abs_photon_times_clock,abs_photon_times_seconds, ...
    rel_photon_times_clock, rel_photon_times_seconds] ...
    = unwrap8BitRawDataFile(path_name,file_name);
% save raw data
save Unwrapped_Data\D2_DCS_AOT_DCS_flow_sample_5 f T duration n num_photons ...
    abs_photon_times_clock abs_photon_times_seconds rel_photon_times_clock ...
    rel_photon_times_seconds

%% Sample 6
file_name = 'sp_10mm_5mW_posBA.dat'; 
% extract raw data
[f,T,duration,n,num_photons,abs_photon_times_clock,abs_photon_times_seconds, ...
    rel_photon_times_clock, rel_photon_times_seconds] ...
    = unwrap8BitRawDataFile(path_name,file_name);
% save raw data
save Unwrapped_Data\D2_DCS_AOT_DCS_flow_sample_6 f T duration n num_photons ...
    abs_photon_times_clock abs_photon_times_seconds rel_photon_times_clock ...
    rel_photon_times_seconds

%% Sample 7 - 16 bit format!!
% need to write function for this!
% file_name = 'sp_10mm_5mW_posCA.dat'; 
% % extract raw data
% [f,T,duration,n,num_photons,abs_photon_times_clock,abs_photon_times_seconds, ...
%     rel_photon_times_clock, rel_photon_times_seconds] ...
%     = unwrap16BitRawDataFile(path_name,file_name);
% % save raw data
% save Unwrapped_Data\D2_DCS_AOT_DCS_flow_sample_7 f T duration n num_photons ...
%     abs_photon_times_clock abs_photon_times_seconds rel_photon_times_clock ...
%     rel_photon_times_seconds

%% Sample 8
file_name = 'sp_10mm_5mW_posDA.dat'; 
% extract raw data
[f,T,duration,n,num_photons,abs_photon_times_clock,abs_photon_times_seconds, ...
    rel_photon_times_clock, rel_photon_times_seconds] ...
    = unwrap8BitRawDataFile(path_name,file_name);
% save raw data
save Unwrapped_Data\D2_DCS_AOT_DCS_flow_sample_8 f T duration n num_photons ...
    abs_photon_times_clock abs_photon_times_seconds rel_photon_times_clock ...
    rel_photon_times_seconds
